// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCLSefeeGMaEcZXjxdVwUGZecY1v_j-Fc',
    appId: '1:322245622706:web:f04bf349d0021469de02ab',
    messagingSenderId: '322245622706',
    projectId: 'mqtt-controller-cfb31',
    authDomain: 'mqtt-controller-cfb31.firebaseapp.com',
    storageBucket: 'mqtt-controller-cfb31.appspot.com',
    measurementId: 'G-PPD0QJ874S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9tMqIn3VvZk5fUMOn2UvVUxB187Wl3yk',
    appId: '1:322245622706:android:c8195f8157b5cdb6de02ab',
    messagingSenderId: '322245622706',
    projectId: 'mqtt-controller-cfb31',
    storageBucket: 'mqtt-controller-cfb31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLRdbNeu_uUE5eCV5AZBqpmmeQBNuk8hk',
    appId: '1:322245622706:ios:93b45984ba5bcf2bde02ab',
    messagingSenderId: '322245622706',
    projectId: 'mqtt-controller-cfb31',
    storageBucket: 'mqtt-controller-cfb31.appspot.com',
    iosBundleId: 'com.example.mqttController',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLRdbNeu_uUE5eCV5AZBqpmmeQBNuk8hk',
    appId: '1:322245622706:ios:93b45984ba5bcf2bde02ab',
    messagingSenderId: '322245622706',
    projectId: 'mqtt-controller-cfb31',
    storageBucket: 'mqtt-controller-cfb31.appspot.com',
    iosBundleId: 'com.example.mqttController',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCLSefeeGMaEcZXjxdVwUGZecY1v_j-Fc',
    appId: '1:322245622706:web:50840d60541e86d5de02ab',
    messagingSenderId: '322245622706',
    projectId: 'mqtt-controller-cfb31',
    authDomain: 'mqtt-controller-cfb31.firebaseapp.com',
    storageBucket: 'mqtt-controller-cfb31.appspot.com',
    measurementId: 'G-SSPB8B3SDB',
  );
}
